### ISSUE TITLE
Option to use more than 20 PU files

### ISSUE THREAD

**Issue by clelange** [CMS-HGCAL/reco-prodtools#21]
This is related to the discussion for #20: it would be nice to allow a different number of files to be used for pileup just to make sure that for larger productions PU events do not repeat.

**Comment by malgeri** [comment]
Hi Clemens,

ok. I'll produce a version with a customizable number of files.
Best,
              l.

**Comment by clelange** [comment]
Closing this, not needed anymore thanks due #47
