### ISSUE TITLE
Add proper flags for PCA/Electron part in ntupler config template

### ISSUE THREAD

**Issue by artlbv** [CMS-HGCAL/reco-prodtools#35]
This is to adapt to this PR https://github.com/CMS-HGCAL/reco-ntuples/pull/51
As I see, one does not simply add the config flag with a default option, but rather an argument?
This is not urgent, but maybe @clelange can clarify next week.

**Comment by clelange** [comment]
Hi @artlbv - I think the easiest way it to use a switch (to flip true/false), as done e.g. in https://github.com/CMS-HGCAL/reco-prodtools/blob/master/SubmitHGCalPGun.py#L48
